---
title: "corr_outputs"
author: "lyan"
date: "May 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Feature correlation investigation

```{r}
setwd('/home/lyan/Documents/sber_housing/')

library(ggplot2)
library(reshape2)
library(corrplot)
library(dplyr)


# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(plots, plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  #plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

train = read.csv('train.csv')
test = read.csv('test.csv')

col_names = colnames(train)
col_names_len = length(colnames(train))

train[is.na(train)] = NaN

sub_train = train[,col_names[1:100]]
cor_matr = cor(sub_train[sapply(sub_train, is.numeric)])
corrplot(cor_matr, method='circle')

# corr analysis

CORR_THRES = 0.25

filter = function(t){
  if (!is.numeric(train[,t])){
    return(FALSE)
  }
  corr = cor(train[,'price_doc'], train[,t])
  return(corr > CORR_THRES && corr < 0.99)
}

res = sapply(col_names, filter)
col_names[(which(as.vector(res) == TRUE))]

# end

#model training
high_cor_feat = col_names[(which(as.vector(res) == TRUE))]

plot_density = function(t){
  p = ggplot(train, aes_string(x='id', y=t)) + geom_line()
  return(p)
}

plots = lapply(high_cor_feat, plot_density)

multiplot(plots, cols=2)

#end

```
